### PR TITLE
[WIP] Add Puli Discovery integration

### PR DESCRIPTION
**Pull request by wouterj**
A very basic Puli discovery implementation, just to start playing around a little with integrating Puli into the Symfony CMF project. This should not be considered for the CMF 1.3 release.

### CODE REVIEW

**Comment by dantleech** [comment]
What do we aim to achieve here?

**Comment by dantleech** [comment]
Just saw your subsequent PR, ignore that last comment.

**Comment by ElectricMaxxx** [comment]
Still relevant/needed?

**Comment by ElectricMaxxx** [comment]
pls reopen if still interessted.

**Pull request closed without merging**
